### PR TITLE
Simpler fix for horizontal scrolling

### PR DESCRIPTION
**Pull request by julienkosinski**
Sorry, it's working fine just like that.

### CODE REVIEW

**Comment by jeevatkm** [comment]
Thanks for your PR.

**Comment by jeevatkm** [comment]
@julienkosinski BTW I thought of asking, if you're interested in contributing to aah framework in someway. Please let me know.

So that I could take help (creating example applications like [these app](https://github.com/go-aah/tutorials)) from you.

**Comment by julienkosinski** [comment]
@jeevatkm Yeah, I think I might be interested in doing so! :) I'll come back in Gitter chat as soon as it is the case.

About the PR don't forget to deploy it :).

**Comment by jeevatkm** [comment]
Thank you! Your PR coming in with next version deploy.

**Pull request merged**
